version: '3'
services:
  base:
    image: "mysql"
    container_name: 'Base_Mysql'
    environment:
      MYSQL_ROOT_PASSWORD: secret
    volumes:
      - base_mysql:/var/lib/mysql      
    ports:
      - "3306:3306"
  backend:
    image: "app_go"
    container_name: 'Backend_Go'
    environment:
      DB_USER: root
      DB_PASSWORD: secret
      DB_HOST: Base_Mysql
      DB_PORT: 3306
      DB_NAME: tarea3_db
    ports:
      - "8000:8000"
volumes:
  base_mysql: 